defaultActionTimeout: 60000
maximumActionTimeout: 360000
maxEntrySizeBytes: 2147483648 # 2 * 1024 * 1024 * 1024
prometheusPort: 9090

backplane:
  redisUri: "redis://redis:6379"
  queues:
    - name: "cpu"
      properties:
        - name: "min-cores"
          value: "*"
        - name: "max-cores"
          value: "*"
worker:
  port: 8981
  publicName: "worker:8981"